# 2026 South African Local Gorvernment Election Analysis
## Evidence-based Machine Learning Analysis of the 2026 Local Gorvernment Election
### Selected Metropolitan Municipality
  **eThekwini Metropolitan Municipality**

### Student Information
**Name and Surname** Thabiso Ngongoma
**Student Number** 22327842
**Subject and Level** Technical Programming 2
**Subject code** TLRP200


## Project Purpose
This projects develops a Python-based data analysis and machine learning solution to estimate selectedd outcomes for the 2026 South African Local Government Election in the eThekwini Metropolitan Municipality.

Tha analysis uses historical municipality election results together with relevant supporting demographic information to investigate historical voting patterns, voter turnout, party perfomance and ward-level outcomes.

The project follows machine learning project life cycle including business understanding, data acquisition, data understanding, data preparation, exploratory data analysis, feature engineering, model development, validation, evaluation and interprepation.

The analysis distinguishes clearly between historical observed results, stimates derived from historical data and model-generated estimates for the 2026 election.

**Important**: The model outputs are statistical estimates and are not presented as political opinions as a definite prediction of which party will gorvern the municipality.

## 1. Business Understanding
# Problem Statement
This project uses historical election and demographic data to estimate selected outcomes for the 4 November 2026 Local Government Election in eThekwini Metropolitan Municipality

The analysis focuses only on the eThekwini Metropolitan Municipality and does not attempt to predict party will gorvern

## 2. Data Acquisition

The project uses two main datasets:
IEC Municipal Election Results: Historical election results for eThekwini Metropolitan Municipality

## Links
**https:results.elections.org.za/home/Downloads/ME.Results


**https://isibaloweb.statssa.gov.za/pages/surveys/pss/sensuses/2022/censuses20222.php


Statistics South African Census 2022: Demographic socioeconomic information as supporting variables

The datasets will be cleaned, assessed and combined where appropriate for the analysis.

## 3. Data Understanding 
The datasets will be inspected to understand their structure, variables, data types and geographical coverage.

The election dataset will be used to analyse party results, wards, voter turnout , while Census 2022 will provide relevant demographic and socioeconomic variables.

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("ETH.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'ETH.csv'

In [6]:
import os

In [7]:
os.listdir()

['-1.14-windows.xml',
 '.anaconda',
 '.android',
 '.arduinoIDE',
 '.cache',
 '.conda',
 '.continuum',
 '.copilot',
 '.cursor',
 '.dotnet',
 '.grasp_settings',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.m2',
 '.nbi',
 '.node_repl_history',
 '.nuget',
 '.packettracer',
 '.platformio',
 '.templateengine',
 '.vscode',
 '.vscode-insiders',
 '2026_eThekwini_Election_Analysis.ipynb',
 'anaconda3',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 8.2.2',
 'ClinicEase',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Machine Learning.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Videos']

In [8]:
os.listdir()

['-1.14-windows.xml',
 '.anaconda',
 '.android',
 '.arduinoIDE',
 '.cache',
 '.conda',
 '.continuum',
 '.copilot',
 '.cursor',
 '.dotnet',
 '.grasp_settings',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.m2',
 '.nbi',
 '.node_repl_history',
 '.nuget',
 '.packettracer',
 '.platformio',
 '.templateengine',
 '.vscode',
 '.vscode-insiders',
 '2026_eThekwini_Election_Analysis.ipynb',
 'anaconda3',
 'AppData',
 'Application Data',
 'Cisco Packet Tracer 8.2.2',
 'ClinicEase',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'ETH.csv',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Machine Learning.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Videos']

In [9]:
df = pd.read_csv("ETH.csv")

In [10]:
df.head()

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ABANTU BATHO CONGRESS,14,11/23/2021 4:26:30 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACADEMIC CONGRESS UNION,0,11/23/2021 4:26:30 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIONSA,0,11/23/2021 4:26:30 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIVE CITIZENS COALITION,0,11/23/2021 4:26:30 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIVISTS MOVEMENT OF SOUTH AFRICA,0,11/23/2021 4:26:30 PM

## Technical Issue and Resolution
During data acquisition, a file path erroe occurred because the ETH.csv dataset was initially stored in the Downloads folder rather than the Juypter Notebook working directory

The issue was resolved by moving the dataset into the same project folder as the notebook. The dataset wwas then successfully loaded into Python using Pandas.

In [11]:
df.shape

(76740, 11)

In [12]:
df.columns

Index(['Province', 'Municipality', 'Ward', 'VotingDistrict',
       'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes',
       'PartyName', 'TotalValidVotes', 'DateGenerated'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76740 entries, 0 to 76739
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Province           76740 non-null  str
 1   Municipality       76740 non-null  str
 2   Ward               76740 non-null  str
 3   VotingDistrict     76740 non-null  int64
 4   VotingStationName  76740 non-null  str
 5   RegisteredVoters   76740 non-null  int64
 6   BallotType         76740 non-null  str
 7   SpoiltVotes        76740 non-null  int64
 8   PartyName          76740 non-null  str
 9   TotalValidVotes    76740 non-null  int64
 10  DateGenerated      76740 non-null  str
dtypes: int64(4), str(7)
memory usage: 14.7 MB

In [14]:
df["BallotType"].value_counts()

BallotType
PR      43750
Ward    32990
Name: count, dtype: int64

In [15]:
df["PartyName"].nunique()

54

In [16]:
df["PartyName"].unique()

<ArrowStringArray>
[             'ABANTU BATHO CONGRESS',            'ACADEMIC CONGRESS UNION',
                           'ACTIONSA',          'ACTIVE CITIZENS COALITION',
 'ACTIVISTS MOVEMENT OF SOUTH AFRICA',          'ADVANCED DYNAMIC ALLIANCE',
        'AFRICA RESTORATION ALLIANCE',          'AFRICAN BASIC REPUBLICANS',
 'AFRICAN CHRISTIAN DEMOCRATIC PARTY',          'AFRICAN DEMOCRATIC CHANGE',
         'AFRICAN FEDERAL CONVENTION',         'AFRICAN FREEDOM REVOLUTION',
       'AFRICAN INDEPENDENT CONGRESS',        'AFRICAN MANTUNGWA COMMUNITY',
          'AFRICAN NATIONAL CONGRESS',               'AFRICAN PEOPLE FIRST',
        'AFRICAN PEOPLE'S CONVENTION',          'AFRICAN PEOPLE'S MOVEMENT',
    'AFRICAN TRANSFORMATION MOVEMENT',                         'AL JAMA-AH',
         'ALLIED MOVEMENT FOR CHANGE',      'AZANIAN PEOPLE'S ORGANISATION',
             'BLACK FIRST LAND FIRST',            'CONGRESS  OF THE PEOPLE',
                'DEMOCRATIC ALLIANCE',        'DEMOCRATIC LIBERAL CONGRESS',
       'DEMOCRATIC PEOPLE'S CONGRESS',          'ECONOMIC FREEDOM FIGHTERS',
           'FORUM 4 SERVICE DELIVERY',                    'GOD SAVE AFRICA',
                               'GOOD',         'INDEPENDENT PEOPLE'S PARTY',
              'INKATHA FREEDOM PARTY',                'INTERNATIONAL PARTY',
       'JUSTICE AND EMPLOYMENT PARTY',                   'KZN INDEPENDENCE',
         'MINORITIES OF SOUTH AFRICA',                     'MINORITY FRONT',
             'NATIONAL FREEDOM PARTY',  'PAN AFRICANIST CONGRESS OF AZANIA',
                 'PATRIOTIC ALLIANCE',             'PEOPLE'S FREEDOM PARTY',
    'PEOPLE'S REVOLUTIONARY MOVEMENT',            'SPECTRUM NATIONAL PARTY',
      'THE ORGANIC HUMANITY MOVEMENT',                     'TRULY ALLIANCE',
  'UNITED CHRISTIAN DEMOCRATIC PARTY',           'UNITED CULTURAL MOVEMENT',
        'UNITED INDEPENDENT MOVEMENT',                 'VRYHEIDSFRONT PLUS',
                        'INDEPENDENT',             'CAPE COLOURED CONGRESS',
                         'LAND PARTY',                   'FEDERAL PARTY SA']
Length: 54, dtype: str

In [18]:
df.groupby("PartyName")["TotalValidVotes"].sum().sort_values(ascending = False).head(15)

PartyName
AFRICAN NATIONAL CONGRESS             653444
DEMOCRATIC ALLIANCE                   402413
ECONOMIC FREEDOM FIGHTERS             162447
INKATHA FREEDOM PARTY                 109447
INDEPENDENT                            32987
ACTIONSA                               29864
ACTIVE CITIZENS COALITION              14264
AFRICAN CHRISTIAN DEMOCRATIC PARTY     11915
ABANTU BATHO CONGRESS                  10864
AFRICAN INDEPENDENT CONGRESS           10333
AFRICAN TRANSFORMATION MOVEMENT         9549
JUSTICE AND EMPLOYMENT PARTY            8722
DEMOCRATIC LIBERAL CONGRESS             8178
AFRICAN DEMOCRATIC CHANGE               7835
MINORITY FRONT                          7561
Name: TotalValidVotes, dtype: int64

In [19]:
df["Ward"].nunique()

111

In [20]:
df["VotingDistrict"].nunique()

875

In [21]:
df["DateGenerated"].unique()

<ArrowStringArray>
['11/23/2021 4:26:30 PM']
Length: 1, dtype: str

In [22]:
df.groupby("PartyName")["TotalValidVotes"].sum().sort_values(ascending = False).head(15)

PartyName
AFRICAN NATIONAL CONGRESS             653444
DEMOCRATIC ALLIANCE                   402413
ECONOMIC FREEDOM FIGHTERS             162447
INKATHA FREEDOM PARTY                 109447
INDEPENDENT                            32987
ACTIONSA                               29864
ACTIVE CITIZENS COALITION              14264
AFRICAN CHRISTIAN DEMOCRATIC PARTY     11915
ABANTU BATHO CONGRESS                  10864
AFRICAN INDEPENDENT CONGRESS           10333
AFRICAN TRANSFORMATION MOVEMENT         9549
JUSTICE AND EMPLOYMENT PARTY            8722
DEMOCRATIC LIBERAL CONGRESS             8178
AFRICAN DEMOCRATIC CHANGE               7835
MINORITY FRONT                          7561
Name: TotalValidVotes, dtype: int64

In [23]:
df.groupby("BallotType")["TotalValidVotes"].sum()

BallotType
PR      774736
Ward    776015
Name: TotalValidVotes, dtype: int64

In [24]:
df["RegisteredVoters"].describe()

count    76740.000000
mean      2183.586591
std       1190.978470
min        107.000000
25%       1358.000000
50%       2056.000000
75%       2823.000000
max       7910.000000
Name: RegisteredVoters, dtype: float64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.isnull().sum()

Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

In [27]:
df["Municipality"].unique()

<ArrowStringArray>
['ETH - eThekwini']
Length: 1, dtype: str

In [28]:
df["Province"].unique()

<ArrowStringArray>
['KwaZulu-Natal']
Length: 1, dtype: str

In [30]:
df["Ward"].head(10)

0    Ward 59500001
1    Ward 59500001
2    Ward 59500001
3    Ward 59500001
4    Ward 59500001
5    Ward 59500001
6    Ward 59500001
7    Ward 59500001
8    Ward 59500001
9    Ward 59500001
Name: Ward, dtype: str

In [33]:
df["VotingDistrict"].head(10)

0    43400179
1    43400179
2    43400179
3    43400179
4    43400179
5    43400179
6    43400179
7    43400179
8    43400179
9    43400179
Name: VotingDistrict, dtype: int64

In [34]:
df["DateGenerated"] = pd.to_datetime(df["DateGenerated"])

In [35]:
df["DateGenerated"].dtype

dtype('<M8[us]')

In [36]:
(df["RegisteredVoters"] < 0).sum()

np.int64(0)

In [37]:
(df["TotalValidVotes"] < 0).sum()

np.int64(0)

In [38]:
(df["SpoiltVotes"] < 0).sum()

np.int64(0)

In [39]:
df["TurnoutRate"] = (
    (df["TotalValidVotes"] + df["SpoiltVotes"])
    / df["RegisteredVoters"]
) * 100

In [40]:
df["TurnoutRate"].describe()

count    76740.000000
mean         1.934594
std          4.604835
min          0.000000
25%          0.454358
50%          0.955921
75%          1.649236
max         96.031746
Name: TurnoutRate, dtype: float64

In [42]:
df.groupby("BallotType").size()

BallotType
PR      43750
Ward    32990
dtype: int64

In [43]:
df.groupby("BallotType")["Ward"].nunique()

BallotType
PR      111
Ward    111
Name: Ward, dtype: int64

In [44]:
df.groupby("BallotType")["VotingDistrict"].nunique()

BallotType
PR      875
Ward    875
Name: VotingDistrict, dtype: int64

In [46]:
df.groupby("BallotType")["PartyName"].nunique()

BallotType
PR      50
Ward    53
Name: PartyName, dtype: int64

In [ ]:
df.groupby("BallotType", "PartyName"

In [48]:
df.groupby(["BallotType", "PartyName"])["TotalValidVotes"].sum().sort_values(ascending = False).head(20)

BallotType  PartyName
PR          AFRICAN NATIONAL CONGRESS             329307
Ward        AFRICAN NATIONAL CONGRESS             324137
PR          DEMOCRATIC ALLIANCE                   203980
Ward        DEMOCRATIC ALLIANCE                   198433
PR          ECONOMIC FREEDOM FIGHTERS              83699
Ward        ECONOMIC FREEDOM FIGHTERS              78748
PR          INKATHA FREEDOM PARTY                  57722
Ward        INKATHA FREEDOM PARTY                  51725
            INDEPENDENT                            32987
PR          ACTIONSA                               18201
Ward        ACTIONSA                               11663
            ACTIVE CITIZENS COALITION               8025
PR          AFRICAN INDEPENDENT CONGRESS            7809
            ACTIVE CITIZENS COALITION               6239
Ward        AFRICAN CHRISTIAN DEMOCRATIC PARTY      6022
PR          AFRICAN CHRISTIAN DEMOCRATIC PARTY      5893
Ward        ABANTU BATHO CONGRESS                   5866
            AFRICAN TRANSFORMATION MOVEMENT         5131
PR          ABANTU BATHO CONGRESS                   4998
            JUSTICE AND EMPLOYMENT PARTY            4763
Name: TotalValidVotes, dtype: int64

In [49]:
df.groupby(["VotingDistrict", "BallotType"])["RegisteredVoters"].nunique().max()

np.int64(1)

In [50]:
df.groupby(["VotingDistrict", "BallotType"])["RegisteredVoters"].first().describe()

count    1750.000000
mean     2181.857143
std      1192.548465
min       107.000000
25%      1356.500000
50%      2054.000000
75%      2821.750000
max      7910.000000
Name: RegisteredVoters, dtype: float64

In [52]:
vd_data = df.groupby (
    ["Province", "Municipality", "Ward", "VotingDistrict", "BallotType"]
).agg(
    RegisteredVoters = ("RegisteredVoters", "first"),
    SpoiltVotes = ("SpoiltVotes", "first"),
    TotalValidVotes = ("TotalValidVotes", "first")
).reset_index()

In [53]:
vd_data.shape

(1750, 8)

In [54]:
vd_data.head()

,Province,Municipality,Ward,VotingDistrict,BallotType,RegisteredVoters,SpoiltVotes,TotalValidVotes
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,2365,12,14
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,Ward,2365,8,19
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400180,PR,1569,6,2
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400180,Ward,1569,6,2
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400191,PR,866,0,1

In [55]:
df.groupby(["VotingDistrict", "BallotType"])["PartyName"].count().describe()

count    1750.000000
mean       43.851429
std         6.281712
min        31.000000
25%        38.000000
50%        46.500000
75%        50.000000
max        50.000000
Name: PartyName, dtype: float64

In [56]:
party_vd = df.groupby (
    ["Province", "Municipality", "Ward", "VotingDistrict", "BallotType", "PartyName"]
)["TotalValidVotes"].sum().reset_index()

In [57]:
party_vd.shape

(76740, 7)

In [58]:
party_vd.head()

,Province,Municipality,Ward,VotingDistrict,BallotType,PartyName,TotalValidVotes
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,ABANTU BATHO CONGRESS,14
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,ACADEMIC CONGRESS UNION,0
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,ACTIONSA,0
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,ACTIVE CITIZENS COALITION,0
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,PR,ACTIVISTS MOVEMENT OF SOUTH AFRICA,0

In [59]:
party_vd.groupby("PartyName")["TotalValidVotes"].sum().sort_values(ascending = False).head(10)

PartyName
AFRICAN NATIONAL CONGRESS             653444
DEMOCRATIC ALLIANCE                   402413
ECONOMIC FREEDOM FIGHTERS             162447
INKATHA FREEDOM PARTY                 109447
INDEPENDENT                            32987
ACTIONSA                               29864
ACTIVE CITIZENS COALITION              14264
AFRICAN CHRISTIAN DEMOCRATIC PARTY     11915
ABANTU BATHO CONGRESS                  10864
AFRICAN INDEPENDENT CONGRESS           10333
Name: TotalValidVotes, dtype: int64

In [61]:
vd_totals = party_vd.groupby (
    ["VotingDistrict", "BallotType"]
)["TotalValidVotes"].sum().reset_index()

In [62]:
vd_totals = vd_totals.rename (
    columns = {"TotalValidVotes": "DistrictValidVotes"}
)

In [63]:
party_vd = party_vd.merge (
    vd_totals,
    on = ["VotingDistrict", "BallotType"],
    how = "left"
)

In [64]:
party_vd["VoteShare"] = (
    party_vd["TotalValidVotes"]
    / party_vd["DistrictValidVotes"]
) * 100

In [65]:
party_vd["VoteShare"].describe()

count    76740.000000
mean         2.280427
std          9.995588
min          0.000000
25%          0.000000
50%          0.000000
75%          0.294985
max         98.002663
Name: VoteShare, dtype: float64

In [68]:
(party_vd["VoteShare"] < 0).sum()

np.int64(0)

In [69]:
model_data = party_vd.copy()

In [70]:
model_data["PartyID"] = model_data["PartyName"].astype("category").cat.codes

In [71]:
top_parties = (
    model_data.groupby("PartyName")["TotalValidVotes"]
    .sum()
    .nlargest(5)
    .index
)

In [73]:
model_data = model_data[model_data["PartyName"].isin(top_parties)]

In [76]:
X = model_data [
    ["VotingDistrict", "BallotType", "RegisteredVoters", "DistrictValidVotes"]
    ].copy()

KeyError: "['RegisteredVoters'] not in index"

In [77]:
model_data.columns

Index(['Province', 'Municipality', 'Ward', 'VotingDistrict', 'BallotType',
       'PartyName', 'TotalValidVotes', 'DistrictValidVotes', 'VoteShare',
       'PartyID'],
      dtype='str')

In [80]:
x = model_data[["VotingDistrict","BallotType","RegisteredVoters","DistrictValidVotes"]]

KeyError: "['RegisteredVoters'] not in index"

In [81]:
X = model_data.iloc[:, [3, 4, 5, 8]]

In [82]:
X.head()

    VotingDistrict BallotType                  PartyName  VoteShare
14        43400179         PR  AFRICAN NATIONAL CONGRESS  86.438923
24        43400179         PR        DEMOCRATIC ALLIANCE   0.103520
27        43400179         PR  ECONOMIC FREEDOM FIGHTERS   7.763975
32        43400179         PR      INKATHA FREEDOM PARTY   0.103520
59        43400179       Ward  AFRICAN NATIONAL CONGRESS  88.659794

In [84]:
X["BallotType"] = X["BallotType"].map({"PR": 0, "Ward": 1})

In [85]:
y = model_data["VoteShare"]

In [86]:
from sklearn.ensemble import RandomForestRegressor

In [88]:
model = RandomForestRegressor(n_estimators = 100, random_state =42)
model.fit(X, y)

ValueError: could not convert string to float: 'AFRICAN NATIONAL CONGRESS'

In [89]:
X["PartyID"] = model_data["PartyID"]

In [90]:
X = X.fillna(0)

In [92]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

ValueError: could not convert string to float: 'AFRICAN NATIONAL CONGRESS'

In [93]:
y.isna().sum()

np.int64(0)

In [94]:
y.isin([float("inf"), float("-inf")]).sum()

np.int64(0)

In [95]:
X.dtypes

VotingDistrict      int64
BallotType          int64
PartyName             str
VoteShare         float64
PartyID              int8
dtype: object

In [96]:
X.isna().sum()

VotingDistrict    0
BallotType        0
PartyName         0
VoteShare         0
PartyID           0
dtype: int64

In [97]:
X = model_data[["VotingDistrict", "BallotType", "RegisteredVoters", "DistrictValidVoters", "PartyID"]].copy()

KeyError: "['RegisteredVoters', 'DistrictValidVoters'] not in index"

In [98]:
X.shape

(7386, 5)

In [99]:
y.shape

(7386,)

In [100]:
from sklearn.linear_model  import LinearRegression

In [101]:
model = LinearRegression()
model.fit(X, y)

ValueError: could not convert string to float: 'AFRICAN NATIONAL CONGRESS'

In [102]:
party_totals = model_data.groupby("PartyName")["TotalValidVotes"].sum().sort_values(ascending = False)

In [103]:
party_totals.head(10)

PartyName
AFRICAN NATIONAL CONGRESS    653444
DEMOCRATIC ALLIANCE          402413
ECONOMIC FREEDOM FIGHTERS    162447
INKATHA FREEDOM PARTY        109447
INDEPENDENT                   32987
Name: TotalValidVotes, dtype: int64

In [104]:
party_share = (party_totals / party_totals.sum()) *100

In [105]:
party_share.head(10)

PartyName
AFRICAN NATIONAL CONGRESS    48.021294
DEMOCRATIC ALLIANCE          29.573143
ECONOMIC FREEDOM FIGHTERS    11.938154
INKATHA FREEDOM PARTY         8.043209
INDEPENDENT                   2.424199
Name: TotalValidVotes, dtype: float64

In [106]:
results = pd.DataFrame ({
    "TotalVotes": party_totals,
    "VoteShare": party_share
})

In [107]:
results["VoteShare"] = results["VoteShare"].round(2)

In [108]:
results.head(10)

                           TotalVotes  VoteShare
PartyName
AFRICAN NATIONAL CONGRESS      653444      48.02
DEMOCRATIC ALLIANCE            402413      29.57
ECONOMIC FREEDOM FIGHTERS      162447      11.94
INKATHA FREEDOM PARTY          109447       8.04
INDEPENDENT                     32987       2.42

In [109]:
results.index[0]

'AFRICAN NATIONAL CONGRESS'

In [110]:
results.iloc[0]["VoteShare"]

np.float64(48.02)

The analysis of the available IEC election results identified the leading party in eThekwini based on observed valid votes and calculated share voes

In [111]:
ward_competition = model_data.groupby("Ward")["VoteShare"].agg(["max", "min"])

In [113]:
ward_competition["Margin"] = ward_competition["max"] - ward_competition["min"]

In [114]:
ward_competition.sort_values("Margin").head(10)

                     max       min     Margin
Ward
Ward 59500028  52.260778  5.573081  46.687697
Ward 59500026  52.439024  3.469080  48.969944
Ward 59500080  59.811482  0.086881  59.724601
Ward 59500078  61.171797  0.000000  61.171797
Ward 59500051  62.218045  0.000000  62.218045
Ward 59500022  62.485549  0.000000  62.485549
Ward 59500044  62.809917  0.000000  62.809917
Ward 59500083  63.122172  0.000000  63.122172
Ward 59500013  63.821138  0.182815  63.638323
Ward 59500085  64.339623  0.651890  63.687732

In [115]:
selected_awards = ward_competition.sort_values("Margin").head(3).index.tolist()

In [116]:
selected_awards

['Ward 59500028', 'Ward 59500026', 'Ward 59500080']

In [118]:
ward_results = model_data[model_data["Ward"].isin(selected_wards)].copy()

NameError: name 'selected_wards' is not defined

In [119]:
selected_wards

NameError: name 'selected_wards' is not defined

In [120]:
total_registered = df["RegisteredVoters"].sum()

In [121]:
total_valid = df["TotalValidVotes"].sum()

In [122]:
total_spoilt = df["SpoiltVotes"].sum()

In [123]:
turnout = ((total_valid + total_spoilt) / total_registered) * 100

In [124]:
turnout

np.float64(1.7900077660807658)